language: node_js
node_js:
  - '12'

services:
  - postgresql

before_script:
  - psql -c "create database grace_shopper;" -U postgres

jobs:
  include:
    -script: npm run lint
    name: 'running ESLint'
